name: enos_portfolio
description: Enos Okello | Software Engineer
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_staggered_animations: ^1.1.1
  go_router: ^12.1.1
  page_transition: ^2.1.0
  flutter_spinkit: ^5.2.0
  webview_flutter: ^4.4.2
  flutter_animated_dialog: ^2.0.1
  animated_text_kit: ^4.2.2
  flutter_staggered_grid_view: ^0.4.1
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  url_launcher: ^6.2.1
  get: ^4.6.6
  universal_html: ^2.2.4
  countup: ^0.1.4
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  lottie: ^3.1.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
    - assets/fonts/

  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttf
          weight: 400
        - asset: assets/fonts/Helvetica-Bold.ttf
          weight: 700

    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 800




